version: '3.3'
services:
  nodejs:
    image: node
    volumes:
       - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
  nginx:
    image: nginx
    ports:
       - 8055:80
    volumes:
       - ./public:/usr/share/nginx/html:ro